name: Run SQL Queries

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-queries:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up MySQL client
      run: sudo apt-get install mysql-client -y

    - name: Run SQL queries
      env:
        DB_HOST: 172.17.0.2
        DB_USER: root
        DB_PASSWORD: root
        DB_NAME: test_db
        DB_PORT: 3132
      run: |
        mysql -h $DB_HOST -P$DB_PORT -u $DB_USER -p$DB_PASSWORD $DB_NAME < sql-scripts/your-queries.sql 
