name: Run SQL Queries

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-queries:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up MySQL client
      run: sudo apt-get install mysql-client -y

    - name: Run SQL queries
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_NAME: ${{ secrets.DB_NAME }}
      run: |
        mysql -h $DB_HOST -u $DB_USER -p$DB_PASSWORD $DB_NAME < /Pipeline_Mysql/sql-scripts/your-queries.sql 
