name: Manual Validation

on:
  workflow_run:
    workflows: ["Run SQL Queries"]
    types:
      - completed

jobs:
  manual-approval:
    runs-on: ubuntu-latest
    steps:
    - name: Await manual approval
      uses: actions/github-script@v6
      with:
        script: |
          const response = await github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'final-deployment.yml',
            ref: context.ref
          });
          console.log(response);

